export const moviesData = [
    {
      id: 1,
      title: "Inception",
      genre: "Sci-Fi",
      director: "Christopher Nolan",
      views: 2000,
      rating: 7,
    },
    {
      id: 2,
      title: "The Shawshank Redemption",
      genre: "Drama",
      director: "Frank Darabont",
      views: 2000,
      rating: 8,
    },
    {
      id: 3,
      title: "Pulp Fiction",
      genre: "Crime",
      director: "Quentin Tarantino",
      views: 4000,
      rating: 6.8,
    },
    {
      id: 4,
      title: "The Godfather",
      genre: "Crime",
      director: "Francis Ford Coppola",
      views: 1000,
      rating: 7.8,
    },
    {
      id: 5,
      title: "The Dark Knight",
      genre: "Action",
      director: "Christopher Nolan",
      views: 5000,
      rating: 9,
    },
  ];