    const mongoose = require("mongoose");

    const postSchema = new mongoose.Schema({
    title: String,
    content: String,
    author: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    });

    const Post = mongoose.model("Post", postSchema);

    module.exports = Post;

    //aLso want to store the data  who is Writing the post so to refernce to that i will do refernce
    //author :{type: mongoose.Schema.Types.ObjectId}
    // here Object Id is the Id generated by the mongoDB
